import { CanadianProvince, CraCategoryCode, CraCategoryInfo, ProvinceTaxInfo, BusinessExpense, CompanyProfile } from '../types';

export const PROVINCES: Record<CanadianProvince, ProvinceTaxInfo> = {
  ON: { code: 'ON', name: 'Ontario', type: 'HST', gstHstRate: 0.13, pstQstRate: 0, totalRate: 0.13 },
  BC: { code: 'BC', name: 'British Columbia', type: 'GST+PST', gstHstRate: 0.05, pstQstRate: 0.07, totalRate: 0.12 },
  AB: { code: 'AB', name: 'Alberta', type: 'GST', gstHstRate: 0.05, pstQstRate: 0, totalRate: 0.05 },
  QC: { code: 'QC', name: 'Quebec', type: 'GST+QST', gstHstRate: 0.05, pstQstRate: 0.09975, totalRate: 0.14975 },
  NS: { code: 'NS', name: 'Nova Scotia', type: 'HST', gstHstRate: 0.15, pstQstRate: 0, totalRate: 0.15 },
  NB: { code: 'NB', name: 'New Brunswick', type: 'HST', gstHstRate: 0.15, pstQstRate: 0, totalRate: 0.15 },
  MB: { code: 'MB', name: 'Manitoba', type: 'GST+PST', gstHstRate: 0.05, pstQstRate: 0.07, totalRate: 0.12 },
  SK: { code: 'SK', name: 'Saskatchewan', type: 'GST+PST', gstHstRate: 0.05, pstQstRate: 0.06, totalRate: 0.11 },
  PE: { code: 'PE', name: 'Prince Edward Island', type: 'HST', gstHstRate: 0.15, pstQstRate: 0, totalRate: 0.15 },
  NL: { code: 'NL', name: 'Newfoundland & Labrador', type: 'HST', gstHstRate: 0.15, pstQstRate: 0, totalRate: 0.15 },
  YT: { code: 'YT', name: 'Yukon', type: 'GST', gstHstRate: 0.05, pstQstRate: 0, totalRate: 0.05 },
  NT: { code: 'NT', name: 'Northwest Territories', type: 'GST', gstHstRate: 0.05, pstQstRate: 0, totalRate: 0.05 },
  NU: { code: 'NU', name: 'Nunavut', type: 'GST', gstHstRate: 0.05, pstQstRate: 0, totalRate: 0.05 },
  OTHER: { code: 'OTHER', name: 'Zero-Rated / Foreign / Exempt', type: 'EXEMPT', gstHstRate: 0, pstQstRate: 0, totalRate: 0 },
};

export const CRA_CATEGORIES: Record<CraCategoryCode, CraCategoryInfo> = {
  '8810': {
    code: '8810',
    line: 'Line 8810',
    name: 'Office Expenses & Supplies',
    description: 'General office supplies, stationery, stamps, pens, printer ink, small equipment.',
    deductiblePercentage: 100,
    suggestedKeywords: ['staples', 'best buy', 'amazon', 'paper', 'printer', 'ink', 'desk', 'walmart'],
  },
  '8811': {
    code: '8811',
    line: 'Line 8810 / SaaS',
    name: 'Software & Cloud Subscriptions',
    description: 'Cloud hosting, SaaS tools, productivity software, domains, cybersecurity.',
    deductiblePercentage: 100,
    suggestedKeywords: ['aws', 'amazon web services', 'google cloud', 'github', 'zoom', 'slack', 'notion', 'microsoft', 'adobe', 'shopify', 'openai', 'figma', 'cloudflare', 'atlassian', 'dropbox'],
  },
  '8521': {
    code: '8521',
    line: 'Line 8521',
    name: 'Advertising & Marketing',
    description: 'Online ads, sponsored posts, marketing materials, business cards, agency fees.',
    deductiblePercentage: 100,
    suggestedKeywords: ['google ads', 'meta', 'facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', 'vistaprint', 'billboard', 'marketing'],
  },
  '8523': {
    code: '8523',
    line: 'Line 8523',
    name: 'Meals & Entertainment (50% Deductible)',
    description: 'CRA allows exactly 50% deduction for food, beverages, and entertainment with clients/business contacts.',
    deductiblePercentage: 50,
    suggestedKeywords: ['tim hortons', 'starbucks', 'mcdonalds', 'restaurant', 'cafe', 'bistro', 'cactus club', 'keg', 'uber eats', 'doordash', 'coffee', 'lunch', 'dinner'],
  },
  '8862': {
    code: '8862',
    line: 'Line 8862',
    name: 'Professional Fees (Legal & Accounting)',
    description: 'Fees paid to lawyers, chartered professional accountants (CPAs), tax preparers, bookkeepers.',
    deductiblePercentage: 100,
    suggestedKeywords: ['deloitte', 'pwc', 'ey', 'kpmg', 'bdo', 'cpa', 'accounting', 'lawyer', 'legal', 'notary', 'paralegal', 'attorney', 'bookkeeper'],
  },
  '8871': {
    code: '8871',
    line: 'Line 8871',
    name: 'Management & Admin Fees',
    description: 'Management, administration, and executive consulting fees paid for operating the business.',
    deductiblePercentage: 100,
    suggestedKeywords: ['management fee', 'admin fee', 'executive fee'],
  },
  '9220': {
    code: '9220',
    line: 'Line 9220',
    name: 'Telephone & Telecommunications',
    description: 'Business cell phone plans, commercial internet, VoIP lines, data services.',
    deductiblePercentage: 100,
    suggestedKeywords: ['rogers', 'bell', 'telus', 'fido', 'koodo', 'freedom mobile', 'virgin plus', 'shaw', 'cogeco', 'starlink', 'voip'],
  },
  '8710': {
    code: '8710',
    line: 'Line 8710',
    name: 'Interest & Bank Charges',
    description: 'Monthly business bank account fees, wire transfer charges, credit card annual fees, loan interest.',
    deductiblePercentage: 100,
    suggestedKeywords: ['rbc', 'td canada trust', 'scotiabank', 'bmo', 'cibc', 'desjardins', 'stripe fee', 'square fee', 'bank charge', 'merchant fee'],
  },
  '8910': {
    code: '8910',
    line: 'Line 8910',
    name: 'Rent & Co-working Space',
    description: 'Office rent, co-working memberships, warehouse lease, dedicated commercial desk.',
    deductiblePercentage: 100,
    suggestedKeywords: ['wework', 'regus', 'spaces', 'lease', 'landlord', 'co-working', 'rent'],
  },
  '9200': {
    code: '9200',
    line: 'Line 9200',
    name: 'Travel & Lodging',
    description: 'Airfare, hotels, taxis, trains for business purposes (out of town).',
    deductiblePercentage: 100,
    suggestedKeywords: ['air canada', 'westjet', 'via rail', 'marriott', 'hilton', 'airbnb', 'uber', 'lyft', 'hotel', 'flight', 'cab'],
  },
  '9281': {
    code: '9281',
    line: 'Line 9281',
    name: 'Motor Vehicle Expenses',
    description: 'Fuel, maintenance, commercial parking, toll charges for business vehicle use.',
    deductiblePercentage: 100,
    suggestedKeywords: ['petro-canada', 'shell', 'esso', 'husky', 'canadian tire', 'parking', '407 etr', 'gas', 'fuel'],
  },
  '8690': {
    code: '8690',
    line: 'Line 8690',
    name: 'Insurance',
    description: 'Commercial general liability (CGL), errors & omissions (E&O), cyber insurance.',
    deductiblePercentage: 100,
    suggestedKeywords: ['intact', 'aviva', 'sun life', 'manulife', 'desjardins insurance', 'co-operators', 'commercial insurance'],
  },
  '8760': {
    code: '8760',
    line: 'Line 8760',
    name: 'Business Licences, Dues & Memberships',
    description: 'Annual corporate filing fees, municipal business licences, professional associations.',
    deductiblePercentage: 100,
    suggestedKeywords: ['corporations canada', 'ontario business registry', 'chamber of commerce', 'license', 'registry', 'membership'],
  },
  '9060': {
    code: '9060',
    line: 'Line 9060',
    name: 'Salaries, Wages & Subcontractors',
    description: 'Payments to freelance developers, designers, virtual assistants, independent contractors.',
    deductiblePercentage: 100,
    suggestedKeywords: ['upwork', 'fiverr', 'contractor', 'consultant', 'developer', 'freelancer', 'payroll'],
  },
  '8960': {
    code: '8960',
    line: 'Line 8960',
    name: 'Repairs & Maintenance',
    description: 'Upkeep and maintenance of commercial equipment and property.',
    deductiblePercentage: 100,
    suggestedKeywords: ['home depot', 'repair', 'maintenance', 'plumbing', 'electrical', 'service technician'],
  },
  '8590': {
    code: '8590',
    line: 'Line 8590',
    name: 'Bad Debts',
    description: 'Amounts that were previously included in income that became uncollectible.',
    deductiblePercentage: 100,
    suggestedKeywords: ['unpaid invoice', 'bad debt', 'uncollectible'],
  },
  '9180': {
    code: '9180',
    line: 'Line 9180',
    name: 'Property Taxes',
    description: 'Taxes on business property.',
    deductiblePercentage: 100,
    suggestedKeywords: ['city of toronto', 'property tax', 'municipal tax'],
  },
  '9270': {
    code: '9270',
    line: 'Line 9270',
    name: 'Other Expenses',
    description: 'Miscellaneous expenses allowable under CRA rules not covered by other lines.',
    deductiblePercentage: 100,
    suggestedKeywords: ['miscellaneous', 'other'],
  },
};

export const COMMON_CANADIAN_VENDORS = [
  { name: 'Amazon Web Services (AWS)', category: '8811' as CraCategoryCode, notes: 'Cloud infrastructure hosting' },
  { name: 'Google Cloud / Google Workspace', category: '8811' as CraCategoryCode, notes: 'Email and cloud services' },
  { name: 'Rogers Communications', category: '9220' as CraCategoryCode, notes: 'Business phone & high-speed internet' },
  { name: 'Bell Canada', category: '9220' as CraCategoryCode, notes: 'Telecommunications & mobility' },
  { name: 'Telus Business', category: '9220' as CraCategoryCode, notes: 'Business internet and phone' },
  { name: 'Staples Canada', category: '8810' as CraCategoryCode, notes: 'Office stationery and printer supplies' },
  { name: 'Tim Hortons', category: '8523' as CraCategoryCode, notes: 'Client meeting coffee & refreshments (50% CRA deductible)' },
  { name: 'Starbucks Canada', category: '8523' as CraCategoryCode, notes: 'Coffee meeting with contractor' },
  { name: 'Uber / Uber Eats', category: '9200' as CraCategoryCode, notes: 'Travel to client site' },
  { name: 'Air Canada', category: '9200' as CraCategoryCode, notes: 'Business flight for trade conference' },
  { name: 'WeWork Canada', category: '8910' as CraCategoryCode, notes: 'Dedicated desk & hotdesk office membership' },
  { name: 'Shopify', category: '8811' as CraCategoryCode, notes: 'E-commerce platform subscription' },
  { name: 'GitHub', category: '8811' as CraCategoryCode, notes: 'Software development code repositories' },
  { name: 'Petro-Canada', category: '9281' as CraCategoryCode, notes: 'Gasoline for commercial deliveries' },
  { name: 'Shell Canada', category: '9281' as CraCategoryCode, notes: 'Fuel for business vehicle' },
  { name: 'Deloitte Canada LLP', category: '8862' as CraCategoryCode, notes: 'Year-end corporate tax return & audit advice' },
  { name: 'RBC Royal Bank', category: '8710' as CraCategoryCode, notes: 'Business operating account monthly service fee' },
  { name: 'TD Canada Trust', category: '8710' as CraCategoryCode, notes: 'Commercial account transaction charges' },
  { name: 'Corporations Canada', category: '8760' as CraCategoryCode, notes: 'Federal annual return filing fee' },
];

export const DEFAULT_COMPANY_PROFILE: CompanyProfile = {
  legalName: 'Northern Maple Solutions Inc.',
  operatingName: 'Northern Maple Tech',
  businessNumber: '893456712 RC0001',
  gstHstNumber: '893456712 RT0001',
  province: 'ON',
  isGstRegistered: true,
  fiscalYearEndMonth: 12,
  accountantName: 'Sarah Jenkins, CPA, CA',
  accountantEmail: 's.jenkins@accountantgroup.ca',
};

export const INITIAL_EXPENSES: BusinessExpense[] = [];

export const SAMPLE_CANADIAN_EXPENSES: BusinessExpense[] = [
  {
    id: 'exp-1',
    companyPaid: 'Amazon Web Services (AWS)',
    amountCad: 284.50,
    date: '2026-08-15',
    craCategory: '8811',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 32.73,
    pstQstAmount: 0,
    netAmount: 251.77,
    deductiblePercentage: 100,
    deductibleAmountCad: 251.77,
    paymentMethod: 'corporate_credit_card',
    hasReceipt: true,
    receiptFileName: 'aws-invoice-aug-2026.pdf',
    notes: 'Production server hosting & PostgreSQL database',
    invoiceNumber: 'INV-AWS-98831',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'exp-2',
    companyPaid: 'Rogers Communications',
    amountCad: 146.90,
    date: '2026-08-18',
    craCategory: '9220',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 16.90,
    pstQstAmount: 0,
    netAmount: 130.00,
    deductiblePercentage: 100,
    deductibleAmountCad: 130.00,
    paymentMethod: 'business_bank_account',
    hasReceipt: true,
    receiptFileName: 'rogers-bill-082026.pdf',
    notes: 'Dedicated gigabit business fiber line',
    invoiceNumber: 'ROG-82910',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-08-18T10:15:00Z',
  },
  {
    id: 'exp-3',
    companyPaid: 'Tim Hortons',
    amountCad: 34.50,
    date: '2026-08-22',
    craCategory: '8523',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 3.97,
    pstQstAmount: 0,
    netAmount: 30.53,
    deductiblePercentage: 50,
    deductibleAmountCad: 15.27, // 50% CRA rule
    paymentMethod: 'corporate_credit_card',
    hasReceipt: true,
    receiptFileName: 'tim-hortons-receipt.jpg',
    notes: 'Breakfast strategy meeting with contractor Alex M.',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-08-22T08:45:00Z',
  },
  {
    id: 'exp-4',
    companyPaid: 'Staples Canada',
    amountCad: 168.40,
    date: '2026-08-27',
    craCategory: '8810',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 19.37,
    pstQstAmount: 0,
    netAmount: 149.03,
    deductiblePercentage: 100,
    deductibleAmountCad: 149.03,
    paymentMethod: 'corporate_credit_card',
    hasReceipt: true,
    receiptFileName: 'staples-order-412.pdf',
    notes: 'Ergonomic mouse, recycled paper, toner cartridge',
    invoiceNumber: 'STP-94819',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-08-27T16:20:00Z',
  },
  {
    id: 'exp-5',
    companyPaid: 'Deloitte Canada LLP',
    amountCad: 1850.00,
    date: '2026-07-10',
    craCategory: '8862',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 212.83,
    pstQstAmount: 0,
    netAmount: 1637.17,
    deductiblePercentage: 100,
    deductibleAmountCad: 1637.17,
    paymentMethod: 'interac_etransfer',
    hasReceipt: true,
    receiptFileName: 'deloitte-cpa-fee-2026.pdf',
    notes: 'T2 Corporate Tax Return Preparation & Compilation Engagement',
    invoiceNumber: 'DEL-2026-0419',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-07-10T11:00:00Z',
  },
  {
    id: 'exp-6',
    companyPaid: 'Google Workspace',
    amountCad: 78.00,
    date: '2026-07-28',
    craCategory: '8811',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 8.97,
    pstQstAmount: 0,
    netAmount: 69.03,
    deductiblePercentage: 100,
    deductibleAmountCad: 69.03,
    paymentMethod: 'corporate_credit_card',
    hasReceipt: true,
    receiptFileName: 'google-workspace-jul26.pdf',
    notes: 'Corporate email seats & shared Google Drive storage',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-07-28T09:00:00Z',
  },
  {
    id: 'exp-7',
    companyPaid: 'Shell Canada',
    amountCad: 92.50,
    date: '2026-08-05',
    craCategory: '9281',
    province: 'ON',
    taxTreatment: 'standard',
    gstHstAmount: 10.64,
    pstQstAmount: 0,
    netAmount: 81.86,
    deductiblePercentage: 100,
    deductibleAmountCad: 81.86,
    paymentMethod: 'director_paid',
    hasReceipt: true,
    receiptFileName: 'shell-gas-receipt.jpg',
    notes: 'Fuel for on-site client hardware setup in Ottawa (Director personal reimbursement)',
    fiscalYear: 2026,
    isDirectorLoan: true,
    createdAt: '2026-08-05T18:10:00Z',
  },
  {
    id: 'exp-8',
    companyPaid: 'RBC Royal Bank',
    amountCad: 26.00,
    date: '2026-08-31',
    craCategory: '8710',
    province: 'OTHER',
    taxTreatment: 'exempt',
    gstHstAmount: 0,
    pstQstAmount: 0,
    netAmount: 26.00,
    deductiblePercentage: 100,
    deductibleAmountCad: 26.00,
    paymentMethod: 'business_bank_account',
    hasReceipt: true,
    notes: 'Commercial checking account monthly maintenance fee (CRA tax exempt)',
    fiscalYear: 2026,
    isDirectorLoan: false,
    createdAt: '2026-08-31T23:59:00Z',
  }
];
